import type { Message } from "@/types";
import { supabase } from "@/lib/supabase";

const STORAGE_KEY = "qqdeni_messages";

// --- Local Storage Implementation (Demo) ---

const SEED_MESSAGES: Partial<Message>[] = [
  { to: "妈妈", from: "小星星", timestamp: Date.now() - 10000000 },
  { to: "爷爷", from: "阿杰", timestamp: Date.now() - 20000000 },
  { to: "小白", from: "匿名", timestamp: Date.now() - 5000000 },
  { to: "My Love", from: "J", timestamp: Date.now() - 800000 },
  { to: "爸爸", from: "匿名", timestamp: Date.now() - 30000000 },
];

function generateId(): string {
  const date = new Date();
  const yyyy = date.getFullYear();
  const mm = String(date.getMonth() + 1).padStart(2, "0");
  const dd = String(date.getDate()).padStart(2, "0");
  const random = Math.floor(100000 + Math.random() * 900000); 
  return `${yyyy}${mm}${dd}${random}`;
}

function seedData(): Message[] {
  const messages: Message[] = [];
  for (let i = 0; i < 50; i++) {
    if (Math.random() < 0.3) {
      const seed = SEED_MESSAGES[Math.floor(Math.random() * SEED_MESSAGES.length)];
      messages.push({
        id: generateId(),
        to: seed.to!,
        from: seed.from!,
        content: "This content is private and cannot be viewed by others.",
        timestamp: seed.timestamp! - Math.random() * 10000000,
        style: Math.floor(Math.random() * 6),
        isPlaceholder: true,
      });
    }
  }
  return messages;
}

const localAdapter = {
  getMessages: async (): Promise<Message[]> => {
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (!raw) {
        const initial = seedData();
        localStorage.setItem(STORAGE_KEY, JSON.stringify(initial));
        return initial;
      }
      return JSON.parse(raw);
    } catch (e) {
      return [];
    }
  },

  saveMessage: async (data: { to: string; content: string; from?: string }): Promise<Message> => {
    const messages = await localAdapter.getMessages();
    const newMessage: Message = {
      id: generateId(), 
      ...data,
      from: data.from || "匿名",
      timestamp: Date.now(),
      style: Math.floor(Math.random() * 6),
      isPlaceholder: false,
    };
    messages.push(newMessage);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(messages));
    return newMessage;
  },

  deleteMessage: async (id: string): Promise<void> => {
    const messages = await localAdapter.getMessages();
    const filtered = messages.filter((m) => m.id !== id);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(filtered));
  },
};

// --- Supabase Implementation (Real Backend) ---

const supabaseAdapter = {
  getMessages: async (): Promise<Message[]> => {
    if (!supabase) return [];
    
    const { data, error } = await supabase
      .from("messages")
      .select("*")
      .order("timestamp", { ascending: true }); // Wall fills up from start

    if (error) {
      console.error("Supabase Error:", error);
      return [];
    }
    return data as Message[];
  },

  saveMessage: async (data: { to: string; content: string; from?: string }): Promise<Message> => {
    if (!supabase) throw new Error("Supabase not configured");

    const newMessage: Partial<Message> = {
      // ID is usually auto-generated by Postgres (UUID), but we use custom string ID.
      // So we generate it client side OR server side.
      // Let's generate client side for consistency with our ID logic.
      id: generateId(),
      to: data.to,
      content: data.content,
      from: data.from || "匿名",
      timestamp: Date.now(),
      style: Math.floor(Math.random() * 6),
      isPlaceholder: false,
    };

    const { data: saved, error } = await supabase
      .from("messages")
      .insert([newMessage])
      .select()
      .single();

    if (error) throw error;
    return saved as Message;
  },

  deleteMessage: async (id: string): Promise<void> => {
    if (!supabase) return;
    const { error } = await supabase.from("messages").delete().eq("id", id);
    if (error) console.error("Supabase Delete Error:", error);
  },
};

// --- Export Adapter ---
// Automatically choose based on configuration
export const storage = supabase ? supabaseAdapter : localAdapter;
